name: CI

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checagem
        uses: actions/checkout@v4

      - name: Configuração do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalação de Dependências
        run: npm install

      - name: Execução de Testes
        run: npm test